### ISSUE TITLE
Létrehozni egy routing táblát

### ISSUE THREAD

**Issue by Abrisss** [szentkiralyi91/RouteSearch#8]
A táblában letároljuk az adatokat az alábbi formában.
Szóval kellenek városok, és kilométerek, és valahogy az útvonalat is el kéne tárolni mellé.
![transit_table](https://cloud.githubusercontent.com/assets/7267276/8126328/dc6056f0-10ed-11e5-97ca-2d1f99a6293b.gif)

**Comment by kukovecz** [comment]
A Routing táblát létrehoztam, de a tökéletes útvonalkereső algoritmus hibái miatt nem a konkrét utak hosszával, hanem a légvonalban vett távolságokkal
